webtalk_init -webtalk_dir F:/GitHub/ECE_449/ECE449_16bitCPU/Project_Files/EX_Stage/EX_Stage.sim/sim_1/behav/xsim/xsim.dir/EX_stage_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 16 23:58:01 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "387befcd-c09f-451c-ae8d-eb6b5aef8919" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "99ad7809dbb847bb817e5c85904b0d98" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "62" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 3900X 12-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7560_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1007221952 -regid "" -xml F:/GitHub/ECE_449/ECE449_16bitCPU/Project_Files/EX_Stage/EX_Stage.sim/sim_1/behav/xsim/xsim.dir/EX_stage_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/GitHub/ECE_449/ECE449_16bitCPU/Project_Files/EX_Stage/EX_Stage.sim/sim_1/behav/xsim/xsim.dir/EX_stage_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/GitHub/ECE_449/ECE449_16bitCPU/Project_Files/EX_Stage/EX_Stage.sim/sim_1/behav/xsim/xsim.dir/EX_stage_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
