webtalk_init -webtalk_dir C:/Users/jakef/Documents/ECE449_16bitCPU/Project_Files/Top_Level_CPU/Top_Level_CPU.sim/sim_1/behav/xsim/xsim.dir/Top_Level_CPU_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 15 16:17:36 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e3f7ead8-75f9-4055-b2bc-dbdfb774b325" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d60582c2051d45858523b6c51ed65df2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "120" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "301 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "11" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8944_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1725509559 -regid "" -xml C:/Users/jakef/Documents/ECE449_16bitCPU/Project_Files/Top_Level_CPU/Top_Level_CPU.sim/sim_1/behav/xsim/xsim.dir/Top_Level_CPU_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jakef/Documents/ECE449_16bitCPU/Project_Files/Top_Level_CPU/Top_Level_CPU.sim/sim_1/behav/xsim/xsim.dir/Top_Level_CPU_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jakef/Documents/ECE449_16bitCPU/Project_Files/Top_Level_CPU/Top_Level_CPU.sim/sim_1/behav/xsim/xsim.dir/Top_Level_CPU_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
